[embedlite-components] Remove usage of Task.jsm. Contributes to JB#55143
sailfishos/embedlite-components pull request #14
Opened 2021-08-25 06:04 UTC by chriadam

Remove uses of Task.jsm from EmbedliteDownloadManager.js as per
Mozilla Bug 1374282. See e.g. 66f6d259bc9ab9416f2de81fbcafe0b76c97bc5c
from gecko-dev tree.

2021-08-25 06:04 UTC, chriadam commented
Needs to be retargeted to sailfishos-esr78 branch once https://github.com/sailfishos/embedlite-components/pull/13 is merged.

2021-08-25 08:03 UTC, mkenttala approved these changes

2021-08-25 08:06 UTC, rainemak requested changes
Actually you should be able to test direct this to the master (esr60 based engine). Please adjust target.

2021-08-29 19:22 UTC, rainemak commented
Please rebase if needed and merge.

2021-08-30 05:04 UTC, merged