Tell the observer if the download is coming from a private tab
sailfishos/embedlite-components pull request #97
Opened 2024-04-08 20:35 UTC by ilpianista

Follow up of [sailfish-browser!1057](https://github.com/sailfishos/sailfish-browser/pull/1057) to propagate the private mode information.

2024-04-18 06:15 UTC, rainemak requested changes
Not quite there yet but close. I think idea to delivere private status to the user interface is good and should be implemented. Provided some guidelines and instructions how this should be improved.

2024-04-18 06:15 UTC, rainemak commented on jscomps/EmbedliteDownloadManager.js
> +const { PrivateBrowsingUtils } = ChromeUtils.import("resource://gre/modules/PrivateBrowsingUtils.jsm");
Not needed as download object itself carries this information. See https://github.com/sailfishos-mirror/gecko-dev/blob/600df6aa643726626d2eab36bc0f6e34bbe5ac2a/toolkit/components/downloads/Downloads.jsm#L80

2024-05-08 09:39 UTC, rainemak commented
Any comments?

2024-05-08 09:42 UTC, ilpianista commented
> Any comments?

I would like to implement your changes, but had no time to work on it. Maybe next week :crossed_fingers:

2024-05-14 20:40 UTC, ilpianista commented on jscomps/EmbedliteDownloadManager.js
> +                                       privateMode: PrivateBrowsingUtils.isContentWindowPrivate(Services.ww.activeWindow) || false,
I'm not sure I understood this, please have a look to my changes. Thanks!

2024-07-09 09:37 UTC, rainemak commented
> I would like to implement your changes, but had no time to work on it. Maybe next week 🤞

Thanks, it's almost there. Easier to explain in form of PR this https://github.com/sailfishos/embedlite-components/pull/98 so I created one. Point is that we need to pass privateMode update from each download message that we send from the embedlite-components to browser app.

2024-09-25 08:52 UTC, closed without merging